---
- hosts: all
  tasks:
    # NOTE(pabelanger): This is kinda hacky, but poetry doesn't have a good
    # way to automate this.
    - name: Update poetry version
      block:
        - name: Setup tox role
          include_role:
            name: tox
          vars:
            tox_envlist: generate_poetry_version
            tox_extra_args: -vv --notest
            tox_install_siblings: false
            zuul_work_dir: "{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"

        - name: Generate version number for poetry
          args:
            chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
            executable: /bin/bash
          shell: "source {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}/.tox/generate_poetry_version/bin/activate; generate-poetry-version"
      when: release_poetry_project is defined

    - name: Run build-python-release role
      include_role:
        name: build-python-release
