---
- hosts: all
  tasks:
    - name: git config user.name
      git_config:
        name: user.name
        scope: global
        value: CaptTrews

    - name: git config user.email
      git_config:
        name: user.email
        scope: global
        value: capttrews@gmail.com
