---
- hosts: localhost
  tasks:
    - name: Ensure tox is installed
      shell: pip install --user tox

    - name: Bootstrap tox environment
      args:
        chdir: "{{ zuul.executor.work_root }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"
      shell: ~/.local/bin/tox -evenv --notest

    - name: Setup tweetrc credentials
      copy:
        content: "{{ twitter_ansible_content.credentials }}"
        dest: ~/.tweetrc

    - name: Send twitter announcement
      args:
        chdir: "{{ zuul.executor.work_root }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"
      shell: ".tox/venv/bin/python tools/twitter-announcement.py 'Version {{ zuul.tag }} of the Ansible {{ zuul.project.short_name }} collection has been released to Ansible Automation hub (https://cloud.redhat.com/ansible/automation-hub/{{ zuul.project.short_name|replace('.', '/') }}) and galaxy (https://galaxy.ansible.com/{{ zuul.projet.short_name|replace('.','/') }}). See the release notes here: https://{{ zuul.project.canonical_name }}/blob/{{ zuul.tag }}/changelogs/CHANGELOG.rst'"
