---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Check for changelog fragments
      args:
        chdir: "{{ zuul.project.src_dir }}"
      shell: git diff --name-only --exit-code changelogs/fragments
      register: r

    - name: Changelog fragment failed
      fail:
        msg: "Your project is missing a changelog fragment, please add one. It should explain to end users the reason for your change."
      when: r.rc == 0
