---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Run emit-job-header role
      include_role:
        name: emit-job-header
      vars:
        zuul_log_url: https://logs.zuul.ansible.com

    - name: Run log-inventory role
      include_role:
        name: log-inventory

- hosts: all:!appliance
  tasks:
    - name: Run add-build-sshkey role (RSA)
      include_role:
        name: add-build-sshkey-fork

    - name: Run add-build-sshkey role
      include_role:
        name: add-build-sshkey-fork (ECDSA)
      vars:
        zuul_ssh_key_algorithm: ecdsa
        zuul_ssh_key_size: 521

    - name: Run start-zuul-console role
      include_role:
        name: start-zuul-console

- hosts: all:!appliance*
  tasks:
    - name: Run prepare-workspace-git role
      include_role:
        name: prepare-workspace-git
